### ISSUE TITLE
Installs RDKit/Code into the wrong directory

### ISSUE THREAD

**Issue by thorlucas** [rdkit/homebrew-rdkit#106]
From RDKit's `FindMyRDKit.cmake`:

```cmake
set(RDKIT_DIR $ENV{RDBASE})
if(NOT RDKIT_DIR)
  message( WARNING "Using RDKit at /home/cosgrove/RDKit_2013_09_1" )
  set(RDKIT_DIR "/home/cosgrove/RDKit_2013_09_1")
endif(NOT RDKIT_DIR)

set(RDKIT_INCLUDE_DIR ${RDKIT_DIR}/Code)
```

In otherwords, RDKit's cmake files look for includes in the $RDBASE/Code directory. Instead, with this we have them in something like `/usr/local/Cellar/rdkit/2020.09.1`. This is incorrect.

**Comment by thorlucas** [comment]
I would suggest running `ln -s /usr/local/Cellar/rdkit/${THE VERSION VAR} /usr/local/share/RDKit/Code` or something

**Comment by thorlucas** [comment]
Also this directory is missing some files that are expected, such as the directory `$RDBASE/Code/cmake`, etc.

**Comment by UnixJunkie** [comment]
I feel this issue is about rdkit, not about the brew installer.
Please open an issue in there: https://github.com/rdkit/rdkit/issues
