### ISSUE TITLE
Invalid option: --with-python3

### ISSUE THREAD

**Issue by aurimas13** [rdkit/homebrew-rdkit#113]
I am trying to install rdkit on my Macbook Pro through brew, but when I run: brew install rdkit --with-python I get this:
Error: Invalid option. 
I am running the newest version of Big Sur (11.2.3). Can you help me to install rdkit with python 3?
As I understand brew removed --with-python, so a question is how to install RDkit with Homebrew?

I will look forward to all the responses.

Sincerely,
Aurimas

**Comment by UnixJunkie** [comment]
try --with-python3 and tell me if it fixes your problem

**Comment by aurimas13** [comment]
Same issue still. It says invalid option: --with-python3

**Comment by UnixJunkie** [comment]
Can you show the exact command you are using, full line?

**Comment by aurimas13** [comment]
Of course.

I am writing this command in terminal:

 brew install rdkit --with-python3

**Comment by UnixJunkie** [comment]
Did you do
```bash
brew tap rdkit/rdkit
```
before?
It is needed.

**Comment by aurimas13** [comment]
Yeah. I've done the command you mentioned but still am getting invalid error when running:

`brew install rdkit --with-python3`

**Comment by UnixJunkie** [comment]
As a workaround, try the conda install method of rdkit.

For the future, can you create a gist showing the full log of your install attempt?

Out of despair, you should try what is mentioned in this paragraph of the README.md file
of this homebrew recipe:
"Forcing brew to install rdkit and all its dependencies from scratch"

**Comment by aurimas13** [comment]
So I've done this:
` brew tap rdkit/rdkit`
followed by 
`brew install rdkit --with-python3`
but am still getting:
`Error: invalid option: --with-python3`

When I tried the installation with conda I don't how to check whether it worked. What should I run to enter rdkit?

Also when I try to install RDKitPostgreSQL I run this:

`conda install -c rdkit rdkit-postgresql` everything is installed followed by
`/Users/Aurimas/opt/anaconda3/envs/my-rdkit-env/bin/initdb -D /folder/where/data/should/be/stored`

and get this:
`creating directory /folder/where/data/should/be/stored ... initdb: error: could not create directory "/folder": Read-only file system`
How this could be solved?

**Comment by YoshitakaMo** [comment]
Now the homebrew-core (default) repository has the rdkit formula (Release 2020.09.4) and it binds to python3 by default.

```
brew untap rdkit/rdkit # if required
brew install rdkit
```

It also has rdkit-postgresql.

See also https://github.com/Homebrew/homebrew-core/blob/master/Formula/rdkit.rb

**Comment by UnixJunkie** [comment]
@aurimas13 
Here is a test script; roundtrip_test.py in this repository:
```
#!/usr/local/bin/python3.9
# we have to use the python interpreter installed by brew...

# quick check that rdkit is installed and working
# upon success, the installed rdkit version is printed out
# upon failure, an assert will fail or some other error will
# be printed out

import rdkit
from rdkit import Chem

in_smi = 'c1ccncc1'
mol = Chem.MolFromSmiles(in_smi)
out_smi = Chem.MolToSmiles(mol)
assert(in_smi == out_smi)
print(rdkit.__version__)
```

**Comment by UnixJunkie** [comment]
The fact that there is a new formula with the same name in the master repository of brew might have broke the current formula
(it is silently ignored/overwritten).

**Comment by UnixJunkie** [comment]
I am closing this, I am sure the formula here supports --with-python3.

**Comment by wenchengxucool** [comment]
still have this problem

**Comment by nirajkamal** [comment]
I have this problem too, after latest Mac upgrade

**Comment by nirajkamal** [comment]
brew install vim --with-python3

this command shows this:
Error: invalid option: --with-python3

**Comment by nirajkamal** [comment]
@UnixJunkie , no it doesn't! it did before, but the latest version doesn't! Please do your research before closing issues.

Options have been removed from Homebrew core formulas and only exist in taps now. See this GitHub issue:
https://github.com/Homebrew/homebrew-core/issues/31510
