### ISSUE TITLE
rdkit with pyenv

### ISSUE THREAD

**Issue by Rnaskan** [rdkit/homebrew-rdkit#114]
I was trying to install rdkit in a specific virtualenv but no success. Is there a way of achieving this goal with this homebrew rdkit package?

**Comment by UnixJunkie** [comment]
I don't think rdkit supports virtualenv (they only support conda currently).
This brew recipe does a system-wide install of rdkit, from source.

**Comment by UnixJunkie** [comment]
cf. https://github.com/rdkit/rdkit/issues/3788
