### ISSUE TITLE
Invalid option --with-python3

### ISSUE THREAD

**Issue by jbibbe4** [rdkit/homebrew-rdkit#115]
I have been following the instruction in the README in order to install RDKit on MacOS Catalina (10.15.7) with Homebrew 3.1.8. I have Python 3.9.4.
`brew tap rdkit/rdkit` worked normally, but `brew install rdkit --with-python3` resulted in the following error: `Error: invalid option: --with-python3`. 

When I type `brew info rdkit`, this is the output:
```
rdkit: stable 2021.03.5 (bottled), HEAD
Open-source chemoinformatics library
https://rdkit.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rdkit.rb
License: BSD-3-Clause
==> Dependencies
Build: cmake ✘, swig ✘
Required: boost ✘, boost-python3 ✘, eigen ✘, freetype ✘, numpy ✘, postgresql ✘, py3cairo ✘, python@3.9 ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
You may need to add RDBASE to your environment variables.
For Bash, put something like this in your $HOME/.bashrc:
  export RDBASE=/usr/local/share/RDKit
==> Analytics
install: 172 (30 days), 476 (90 days), 1,264 (365 days)
install-on-request: 172 (30 days), 475 (90 days), 1,259 (365 days)
build-error: 0 (30 days)
```
So the only option that they give is `--HEAD`, not `--with-python3`. Does this have to do with [Homebrew removing options](https://github.com/Homebrew/brew/issues/5732)? 
How can I install rdkit with the Python 3 wrapper?

**Comment by jbibbe4** [comment]
I don't understand this at all, but when I do 

```
brew install rdkit/rdkit/rdkit --with-python3
```

it works. 
Maybe I should have typed `brew tap rdkit/rdkit/rdkit` instead of only twice rdkit.

My clue for this was that when I typed `brew options --all`, I got:
```
rdkit/rdkit/rdkit
--with-avalon
	Build with Avalon support
--with-inchi
	Build with InChI support
--with-java
	Build Java wrapper
--with-postgresql
	Build with PostgreSQL database cartridge
--with-pycairo
	Build with py2cairo/py3cairo support
--with-python3
	Build with python3 support
--without-eigen
	Build without eigen support
--without-numpy
	Use your own numpy instead of Homebrew's numpy
--HEAD
	Install HEAD version 
```

**Comment by UnixJunkie** [comment]
There is an official brew formula that doesn't require 'brew tap rdkit/rdkit'.
It supports python by default, you should give it a try.

**Comment by jbibbe4** [comment]
> There is an official brew formula that doesn't require 'brew tap rdkit/rdkit'.
> It supports python by default, you should give it a try.

Why isn't that in the README? 

I'm sorry, I'm quite new to Homebrew and its terminology.

**Comment by UnixJunkie** [comment]
Just updated the README; that will save me some user support indeed. :)
