### ISSUE TITLE
New python detection only works with homebrew python

### ISSUE THREAD

**Issue by cainja** [rdkit/homebrew-rdkit#14]
We are trying to install rdkit using the default MacOS X system Python instead of homebrew brewed Python.  (Most other recipes work both ways, and in general hombrew supports both options).

We used to succeed with this, but since commit 49aafe9a3f330f6abec88b3cfedc2df44f477dcb  it doesn't work - I think the `python_executable = "#{HOMEBREW_PREFIX}/bin/python"` line is the problem.

c.c. @rwest @pierrelb

**Comment by UnixJunkie** [comment]
this could be closed
