### ISSUE TITLE
conda-rdkit incomplete?

### ISSUE THREAD

**Issue by soerendip42** [rdkit/homebrew-rdkit#22]
Hi,

I am using conda and rdkit, so  installed
https://github.com/rdkit/conda-rdkit 
with 
conda build boost
conda build rdkit

The installation seems to be successfull, at least in part, since I can import and use rdkit. 

However, I think the version of RDKit is incomplete, since there are no fr_ functions in Chem.Descriptors and when I import rdkit.Chem.PandasTools I get: 
[Errno 2] No such file or directory: '/home/.../Programme/anaconda/envs/_build/share/RDKit/Data/Salts.txt'

Is this version incomplete?

**Comment by teramind** [comment]
I noticed also a strange behaviour.
When I activate a  conda enviromnment and import rdkit from ipython notebook, the kernel will crash.
Apparently, I have to use the system python version at /usr/bin/python in import the packages installed with conda. I don't think both things are related though.

**Comment by greglandrum** [comment]
Hi, were you intended to file this in the conda-rdkit issue tracker?

**Comment by teramind** [comment]
Sure, did it already.

**Comment by greglandrum** [comment]
I don't see it over there:
https://github.com/rdkit/conda-rdkit/issues
