### ISSUE TITLE
OSX 10.10.2 Issue?

### ISSUE THREAD

**Issue by huwdjones** [rdkit/homebrew-rdkit#23]
Hi,

Is there a problem with the formula. I'm using Yosemite OSX 10.10.2? See below for output:

(venv)MacBook-Pro:~ $ brew tap rdkit/rdkit
Cloning into '/usr/local/Library/Taps/rdkit/homebrew-rdkit'...
remote: Counting objects: 221, done.
remote: Total 221 (delta 0), reused 0 (delta 0), pack-reused 221
Receiving objects: 100% (221/221), 35.39 KiB | 0 bytes/s, done.
Resolving deltas: 100% (53/53), done.
Checking connectivity... done.
Tapped 1 formula

(venv)MacBook-Pro:~ $ brew install --HEAD rdkit
==> Installing rdkit from rdkit/homebrew-rdkit
rdkit: Unsatisfied dependency: numpy
Homebrew does not provide Python dependencies; install with:
  pip install numpy
Error: An unsatisfied requirement failed this build.

(venv)MacBook-Pro:~ $ pip install numpy
Collecting numpy
  Downloading numpy-1.9.2-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |################################| 3.7MB 127kB/s 
Installing collected packages: numpy

Successfully installed numpy-1.9.2

(venv)MacBook-Pro:~ $ brew install --HEAD rdkit
==> Installing rdkit from rdkit/homebrew-rdkit
==> Installing dependencies for rdkit: cmake, wget, boost, boost-python
==> Installing rdkit dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.2.1.yosemite.bottle
######################################################################## 100.0%
==> Pouring cmake-3.2.1.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/cmake/3.2.1: 1847 files,  32M
==> Installing rdkit dependency: wget
==> Downloading https://homebrew.bintray.com/bottles/wget-1.16.3.yosemite.bottle
######################################################################## 100.0%
==> Pouring wget-1.16.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/wget/1.16.3: 9 files, 1.5M
==> Installing rdkit dependency: boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.57.0.yosemite.bottl
######################################################################## 100.0%
==> Pouring boost-1.57.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.57.0: 10572 files, 439M
==> Installing rdkit dependency: boost-python
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boo
############################                                              39.6%^C
(venv)Huws-MacBook-Pro:~ huwdjones$ brew install --HEAD rdkit
==> Installing rdkit from rdkit/homebrew-rdkit
==> Installing rdkit dependency: boost-python
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.57.0/boo
######################################################################## 100.0%
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost-python/1.57.0 --libdir=/usr/
==> ./b2 --build-dir=build-python --stagedir=stage-python python=2.7 --prefix=/u
🍺  /usr/local/Cellar/boost-python/1.57.0: 5 files,  11M, built in 90 seconds
==> Installing rdkit
==> Cloning https://github.com/rdkit/rdkit.git
Cloning into '/Library/Caches/Homebrew/rdkit--git'...
remote: Counting objects: 2632, done.
remote: Compressing objects: 100% (2169/2169), done.
remote: Total 2632 (delta 543), reused 1541 (delta 387), pack-reused 0
Receiving objects: 100% (2632/2632), 23.32 MiB | 683.00 KiB/s, done.
Resolving deltas: 100% (543/543), done.
Checking connectivity... done.
==> Checking out branch master
==> cmake -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/rdkit/HEAD' -DCMAKE_BUILD_TY
==> make
Linking CXX shared library ../../lib/libCatalogs.dylib
[ 10%] Built target Catalogs
Linking CXX shared library ../../lib/libDataStructs.dylib
[ 10%] Built target DataStructs
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/rdkit/homebrew-rdkit/issues

(venv)MacBook-Pro:~ $ brew doctor
Your system is ready to brew.
(venv)MacBook-Pro:~ $ brew update
Already up-to-date.
(venv)MacBook-Pro:~ $ brew install --HEAD rdkit
==> Installing rdkit from rdkit/homebrew-rdkit
==> Cloning https://github.com/rdkit/rdkit.git
Updating /Library/Caches/Homebrew/rdkit--git
==> Checking out branch master
==> cmake -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/rdkit/HEAD' -DCMAKE_BUILD_TY
==> make
Linking CXX shared library ../../lib/libCatalogs.dylib
[ 10%] Built target Catalogs
Linking CXX shared library ../../lib/libDataStructs.dylib
[ 10%] Built target DataStructs
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/rdkit/homebrew-rdkit/issues

(venv)MacBook-Pro:~ $ brew install --HEAD rdkit --with-java
==> Installing rdkit from rdkit/homebrew-rdkit
==> Installing dependencies for rdkit: pcre, swig
==> Installing rdkit dependency: pcre
==> Downloading https://homebrew.bintray.com/bottles/pcre-8.36.yosemite.bottle.t
######################################################################## 100.0%
==> Pouring pcre-8.36.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.36: 146 files, 5.9M
==> Installing rdkit dependency: swig
==> Downloading https://homebrew.bintray.com/bottles/swig-3.0.5.yosemite.bottle.
######################################################################## 100.0%
==> Pouring swig-3.0.5.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/swig/3.0.5: 727 files, 7.1M
==> Installing rdkit
==> Cloning https://github.com/rdkit/rdkit.git
Updating /Library/Caches/Homebrew/rdkit--git
==> Checking out branch master
==> mkdir External/java_lib
==> curl http://search.maven.org/remotecontent?filepath=junit/junit/4.11/junit-4
==> cmake -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/rdkit/HEAD' -DCMAKE_BUILD_TY
==> make
                                                                                  ^
15 errors generated.
make[2]: *** [Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap.dir/src/org/RDKit/GraphMolJavaJAVA_wrap.cxx.o] Error 1
make[1]: *** [Code/JavaWrappers/gmwrapper/CMakeFiles/GraphMolWrap.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/rdkit/homebrew-rdkit/issues

(venv)Huws-MacBook-Pro:~ huwdjones$ brew --version
0.9.5
(venv)Huws-MacBook-Pro:~ huwdjones$ brew install rdkit
==> Installing rdkit from rdkit/homebrew-rdkit
==> Downloading https://github.com/rdkit/rdkit/archive/Release_2014_09_2.tar.gz
######################################################################## 100.0%
==> cmake -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/rdkit/2014.09.2' -DCMAKE_BUI
==> make
Linking CXX shared library ../../lib/libCatalogs.dylib
[ 12%] Built target Catalogs
Linking CXX shared library ../../lib/libDataStructs.dylib
[ 12%] Built target DataStructs
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/rdkit/homebrew-rdkit/issues

**Comment by mcs07** [comment]
I think the `--with-java` option hasn't worked for a while. But `brew install rdkit` and `brew install rdkit --HEAD` should both work fine.

Could you try doing `brew install rdkit --HEAD --verbose --debug` and post the full output?

**Comment by huwdjones** [comment]
(venv)MacBook-Pro:~ $ brew install rdkit --HEAD --verbose --debug
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/rdkit/homebrew-rdkit/Formula/rdkit.rb
==> Installing rdkit from rdkit/homebrew-rdkit
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/wget.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/xz.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/makedepend.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost-python.rb
/usr/bin/env python -c import numpy
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/rdkit/homebrew-rdkit/Formula/rdkit.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/boost-python.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/cmake.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/wget.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/xz.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/makedepend.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/git.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/python.rb
/usr/bin/env python -c import numpy
==> Cloning https://github.com/rdkit/rdkit.git
git --git-dir /Library/Caches/Homebrew/rdkit--git/.git status -s
Updating /Library/Caches/Homebrew/rdkit--git
git config remote.origin.url https://github.com/rdkit/rdkit.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at d3d362a merge master
==> Checking out branch master
==> cmake -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/rdkit/HEAD' -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -Wno-dev -DRDK_INSTALL_INTREE=OFF -DRDK_BUILD_CPP_TESTS=OFF -DRDK_INSTALL_STATIC_LIBS=OFF -DPYTHON_EXECUTABLE='/venv/bin/python' -DPYTHON_INCLUDE_DIR='/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7' -DPYTHON_LIBRARY='/venv/bin/../lib/libpython2.7.dylib' -DPYTHON_NUMPY_INCLUDE_PATH='/venv/lib/python2.7/site-packages/numpy/core/include' .
-- The C compiler identification is AppleClang 6.0.0.6000057
-- The CXX compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang
-- Check for working C compiler: /usr/local/Library/ENV/4.3/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found PythonInterp: /venv/bin/python (found version "2.7.9") 
-- Found PythonLibs: /venv/lib/libpython2.7.dylib (found version "2.7.9") 
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   python
Python Install directory /usr/local/Cellar/rdkit/HEAD/lib/python2.7/site-packages
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/rdkit20150404-6468-ri0mgh
==> make
Scanning dependencies of target inchi_support
Scanning dependencies of target hc
[  1%] [  1%] Building C object Code/ML/Cluster/Murtagh/CMakeFiles/hc.dir/hc.c.o
[  1%] Building C object Code/ML/Cluster/Murtagh/CMakeFiles/hc.dir/hcdriver.c.o
Built target inchi_support
Linking C shared library ../../../../lib/libhc.dylib
Scanning dependencies of target ChemicalFeatures
Scanning dependencies of target RDGeneral
[  2%] Building CXX object Code/ChemicalFeatures/CMakeFiles/ChemicalFeatures.dir/FreeChemicalFeature.cpp.o
Scanning dependencies of target RDBoost
[  2%] [  3%] [  3%] [  3%] [  4%] Building CXX object Code/RDGeneral/CMakeFiles/RDGeneral.dir/types.cpp.o
Building CXX object Code/RDGeneral/CMakeFiles/RDGeneral.dir/Invariant.cpp.o
Building CXX object Code/RDGeneral/CMakeFiles/RDGeneral.dir/utils.cpp.o
Building CXX object Code/RDGeneral/CMakeFiles/RDGeneral.dir/RDLog.cpp.o
Building CXX object Code/RDGeneral/CMakeFiles/RDGeneral.dir/Dict.cpp.o
[  4%] Built target hc
make[2]: *** No rule to make target `/venv/lib/libpython2.7.dylib', needed by `lib/libRDBoost.2015.03.1pre.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[  5%] Building CXX object Code/RDBoost/CMakeFiles/RDBoost.dir/Wrap.cpp.o
Linking CXX shared library ../../lib/libChemicalFeatures.dylib
[  5%] Built target ChemicalFeatures
Linking CXX shared library ../../lib/libRDGeneral.dylib
[  5%] Built target RDGeneral
Scanning dependencies of target EigenSolvers
Scanning dependencies of target SimDivPickers
Scanning dependencies of target DataStructs
[  5%] [  5%] Building CXX object Code/Numerics/EigenSolvers/CMakeFiles/EigenSolvers.dir/PowerEigenSolver.cpp.o
[  6%] [  6%] Building CXX object Code/SimDivPickers/CMakeFiles/SimDivPickers.dir/DistPicker.cpp.o
Building CXX object Code/SimDivPickers/CMakeFiles/SimDivPickers.dir/MaxMinPicker.cpp.o
Building CXX object Code/SimDivPickers/CMakeFiles/SimDivPickers.dir/HierarchicalClusterPicker.cpp.o
Scanning dependencies of target Catalogs
make[1]: *** [Code/RDBoost/CMakeFiles/RDBoost.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] [  7%] [  7%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/SparseBitVect.cpp.o
Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/BitVect.cpp.o
Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/ExplicitBitVect.cpp.o
[  7%] Building CXX object Code/Catalogs/CMakeFiles/Catalogs.dir/Catalog.cpp.o
[  8%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/Utils.cpp.o
[  9%] Building CXX object Code/Catalogs/CMakeFiles/Catalogs.dir/CatalogParams.cpp.o
[  9%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/base64.cpp.o
Linking CXX shared library ../../lib/libSimDivPickers.dylib
[  9%] Built target SimDivPickers
[  9%] Building CXX object Code/Catalogs/CMakeFiles/Catalogs.dir/CatalogEntry.cpp.o
[ 10%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/BitOps.cpp.o
Linking CXX shared library ../../../lib/libEigenSolvers.dylib
[ 10%] [ 10%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/DiscreteDistMat.cpp.o
Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/DiscreteValueVect.cpp.o
[ 10%] Built target EigenSolvers
Linking CXX shared library ../../lib/libCatalogs.dylib
[ 10%] Built target Catalogs
Linking CXX shared library ../../lib/libDataStructs.dylib
[ 10%] Built target DataStructs
make: *** [all] Error 2
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
==> Formula
Tap: rdkit/homebrew-rdkit
Path: /usr/local/Library/Taps/rdkit/homebrew-rdkit/Formula/rdkit.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 3e2a79a38e459b3e85dcc50fdb1864c4fc9e6a1e
Last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: 8-core 64-bit haswell
OS X: 10.10.2-x86_64
Xcode: N/A
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /venv/bin/python => /venv/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.6.0_65
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /venv/bin:/venv/bin:/usr/local/Library/ENV/4.3:/usr/local/opt/cmake/bin:/usr/local/opt/wget/bin:/usr/local/opt/python/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: rdkit HEAD did not build
Logs:
     /Library/Logs/Homebrew/rdkit/01.cmake
     /Library/Logs/Homebrew/rdkit/01.cmake.cc
     /Library/Logs/Homebrew/rdkit/02.make
     /Library/Logs/Homebrew/rdkit/02.make.cc
     /Library/Logs/Homebrew/rdkit/CMakeCache.txt

**Comment by mcs07** [comment]
Ah, I think the problem is caused by the virtualenv. See https://github.com/rdkit/homebrew-rdkit/issues/20 for a workaround that might help.

**Comment by huwdjones** [comment]
Ah yes thanks. I found I had to use the native python when installing the RDKit formula. Then create the virtualenv and then copy the libraries into the new virtualenv. I found that installing python with brew and attempting this failed. Thanks for your help.
