### ISSUE TITLE
Having trouble installing rdkit on Mac OS X 10.10.3

### ISSUE THREAD

**Issue by shenkin** [rdkit/homebrew-rdkit#24]
Hi,

I'm having trouble installing RDKit on a Mac running Yosemite 10.10.3.

I first built a Python virtualenv based on my system installation and 
activated it.

The first effort to "brew install rdkit" seemd to implicate boost as the
cause of failure, so I uninstalled and rebuilt boost, which appeared to 
succeed. 

When trying again to intall rdkit, it failed with the following in 
~/Library/Logs/Homebrew/rdkit/02.make:

    [  8%] Building CXX object Code/Catalogs/CMakeFiles/Catalogs.dir/Catalog.cpp.o
    make[1]: *** [Code/RDBoost/CMakeFiles/RDBoost.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [  8%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/ExplicitBitVect.cpp.o
    [  9%] [  9%] Building CXX object Code/Catalogs/CMakeFiles/Catalogs.dir/CatalogParams.cpp.o
    Building CXX object Code/Catalogs/CMakeFiles/Catalogs.dir/CatalogEntry.cpp.o
    [ 10%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/Utils.cpp.o
    Linking CXX shared library ../../lib/libSimDivPickers.dylib
    [ 10%] [ 11%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/base64.cpp.o
    Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/BitOps.cpp.o
    [ 11%] Built target SimDivPickers
    [ 11%] Linking CXX shared library ../../../lib/libEigenSolvers.dylib
    [ 12%] Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/DiscreteDistMat.cpp.o
    Building CXX object Code/DataStructs/CMakeFiles/DataStructs.dir/DiscreteValueVect.cpp.o
    [ 12%] Built target EigenSolvers
    Linking CXX shared library ../../lib/libCatalogs.dylib
    [ 12%] Built target Catalogs
    Linking CXX shared library ../../lib/libDataStructs.dylib
    [ 12%] Built target DataStructs
    make: *** [all] Error 2

When I run the commands:

    python-config --prefix
    find /usr/local/Cellar/rdkit -name rdBase.so -exec otool -L {} \;
    find /usr/local/Cellar/boost -name libboost_python-mt.dylib -exec otool -L {} \;

I get:

    > python-config --prefix
    /System/Library/Frameworks/Python.framework/Versions/2.7
    > find /usr/local/Cellar/rdkit -name rdBase.so -exec otool -L {} \;
    find: /usr/local/Cellar/rdkit: No such file or directory
    > find /usr/local/Cellar/boost -name libboost_python-mt.dylib -exec otool -L {} \;
    > 

Any suggestions?

**Comment by mcs07** [comment]
Probably caused by the virtualenv. See https://github.com/rdkit/homebrew-rdkit/issues/20 for more info.

**Comment by shenkin** [comment]
Sounds good. I will try Anaconda. Reponse appreciated.

**Comment by shenkin** [comment]
I have given up on virtualenv-like things and just want to try brew with the system Python. I am still encountering problems, but will post them elsewhere following a search. Closing this case in the meantime.
