### ISSUE TITLE
Mac 10.10.3; make fails with "ld: symbol(s) not found for architecture x86_64"

### ISSUE THREAD

**Issue by shenkin** [rdkit/homebrew-rdkit#26]
This is the system Python:

> file /usr/bin/Python
> /usr/bin/Python: Mach-O universal binary with 2 architectures
> /usr/bin/Python (for architecture x86_64):  Mach-O 64-bit executable x86_64
> /usr/bin/Python (for architecture i386):    Mach-O executable i386

The gist is: https://gist.github.com/anonymous/642d2eac204664149543

Ideas welcome....

**Comment by UnixJunkie** [comment]
this is so old, I guess it can be closed
