### ISSUE TITLE
Issue with CTest post installation with homebrew

### ISSUE THREAD

**Issue by dmoccia** [rdkit/homebrew-rdkit#27]
I am running into some post installation issues on my mac (OS 10.9.5).  I was hoping to use brew install and then follow this [post] (https://github.com/rdkit/homebrew-rdkit/issues/20) to use rdkit in a virtualenv.

From what I can tell my installation went ok:

==> Installing rdkit from rdkit/homebrew-rdkit
==> Downloading https://github.com/rdkit/rdkit/archive/Release_2015_03_1.tar.gz
Already downloaded: /Library/Caches/Homebrew/rdkit-2015.03.1.tar.gz
==> cmake -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/rdkit/2015.03.1' -DCMAKE_BUI
==> make
==> make install
==> Caveats
You may need to add RDBASE to your environment variables.
For Bash, put something like this in your $HOME/.bashrc

  export RDBASE=/usr/local/share/RDKit

When I CD to RDBASE I see the following directories:

Contrib
Data
Docs
Projects

I cd'd to the Projects directory and ran ctest but got the following:

*Test project /usr/local/share/RDKit/Projects
    Start 1: pythonTestDbCLI
1/1 Test #1: pythonTestDbCLI ..................***Failed    0.02 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec*

I also checked out the directory usr/local/Cellar/rdkit/2015.03.1/lib/python2.7/site-packages/rdkit and tried a ctest here

 Start 1: pythonTestDirML
1/6 Test #1: pythonTestDirML ..................***Failed    0.01 sec
    Start 2: pythonTestDirDataStructs
2/6 Test #2: pythonTestDirDataStructs .........***Failed    0.01 sec
    Start 3: pythonTestDirDbase
3/6 Test #3: pythonTestDirDbase ...............***Failed    0.01 sec
    Start 4: pythonTestDirSimDivFilters
4/6 Test #4: pythonTestDirSimDivFilters .......***Failed    0.01 sec
    Start 5: pythonTestDirVLib
5/6 Test #5: pythonTestDirVLib ................***Failed    0.01 sec
    Start 6: pythonTestDirChem
6/6 Test #6: pythonTestDirChem ................***Failed    0.01 sec

0% tests passed, 6 tests failed out of 6

Total Test time (real) =   0.09 sec

Part of this may just be my ignorance of using a mac (transitioning from windows) but any help you can provide is much appreciated.  Thank you again, 

Dennis

**Comment by dmoccia** [comment]
I may be making progress, will update soon.

**Comment by dmoccia** [comment]
Nope.  Is it possible that this info has something to do with my issue?  I thought I ran this but I do not see anything in the directory I created.

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/dennismoccia/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")'

**Comment by greglandrum** [comment]
Hi Dennis,

I don't think it's really worth the trouble to run the ctests after doing a homebrew build. The environment isn't really set up properly to do this and it will take some doing to get it that way.

Is there any particular reason you want to run the tests?

**Comment by dmoccia** [comment]
Hi Greg

Thank you for the rapid response.  So I thought it was a good practice to perform a ctest after installation, I think I was trying to combine the homebrew install and the general installation from the RDKit site.   I have everything working now, I think I need to clean up my homebrew/python installs a bit though as this is what was causing some of my problems.  Again many thanks

Dennis
