### ISSUE TITLE
Suggestion for Readme update

### ISSUE THREAD

**Issue by supern8ent** [rdkit/homebrew-rdkit#29]
First, cheers to you devs for producing this delicious brew.

This is just a suggestion for the README. I got difficult-to-interpret errors installing because I was using a virtualenv. Also, it was not clear how to tell it to compile for py3. My commands that got it working:

```
deactivate
brew install python3
pip3 install --upgrade pip setuptools
pip3 install pandas    # simply pip3 install numpy would probably work
brew install --with-inchi --with-python3 rdkit
cd ~/.virtualenvs/myenv/lib/python3.5/site-packages   # "myenv is the name of the virtualenv
ln -s /usr/local/Cellar/rdkit/2015.09.2/lib/python3.5/site-packages/rdkit
```

Another note: in my virtualenv I did `pip install pillow` to get molecule drawing in jupyter to work.

**Comment by t1m0thy** [comment]
Thanks for this tip.  I got tripped up by running brew from inside a virtualenv as well.  deactivating first did the trick.

**Comment by UnixJunkie** [comment]
To improve the README file, you could send a pull request.
So, this issue could be closed.
