### ISSUE TITLE
Homebrew installs old version of RDKit

### ISSUE THREAD

**Issue by tdudgeon** [rdkit/homebrew-rdkit#39]
Currently the versions that gets installed is Release_2016_03_3.
Are there plans to switch to the latest release?

**Comment by hsiaoyi0504** [comment]
For people interested in installing different releases, you can do following things:
After you tap the repo `brew tap rdkit/rdkit`
`brew edit rdkit`
Change the 5th and 6th lines:
For example, the 2017_03_3 release can be installed using following url and sha256:
```
  url "https://github.com/rdkit/rdkit/archive/Release_2017_03_3.tar.gz"
  sha256 "fd9f1fb51c75c6d44f8d5a5de46139af82ed22e93f90bfdf788e2a4096fd897c"
```

sha256 can be got from `shasum -a 256 some_tarball.tar.gz`

The url can be found in [the release page of rdkit](https://github.com/rdkit/rdkit/releases).
Download the version you are interested in and use `shasum` command to get sha256.
