### ISSUE TITLE
Python behavior will be changed in homebrew

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/homebrew-rdkit#55]
https://brew.sh/2018/01/19/homebrew-1.5.0/

> On 1st March 2018 the python formula will be upgraded to Python 3.x and a python@2 formula will be added for installing Python 2.7 (although this will be keg-only so neither python nor python2 will be added to the PATH by default without a manual brew link --force). We will maintain python2, python3 and python@3 aliases. Any formulae that use depends_on "python" outside Homebrew/core will need to be updated at this point if they wish to keep using Python 2. Note: macOS has provided Python 2.7 since OS X Lion (10.7) so you can update formulae that need Python 2 today by removing depends_on "python" so they use the system python instead.

It will cause problem for current implementation.

**Comment by hsiaoyi0504** [comment]
I think we need to fix this ...
My Travis CI of my fork https://travis-ci.org/hsiaoyi0504/homebrew-rdkit shows the problem.

**Comment by mcs07** [comment]
Does this fix the problem:

https://discourse.brew.sh/t/python-and-pep-394/1813

**Comment by greglandrum** [comment]
It looks like the change is now breaking the travis builds of the rdkit homebrew recipe.
Any suggestions as to how we can fix it?

**Comment by hsiaoyi0504** [comment]
@greglandrum I will start working on it.

**Comment by hsiaoyi0504** [comment]
There are two different `boost-python` formulas now.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python3.rb
