### ISSUE TITLE
Should we change the way of installation? Install python2 and python3 at the same time by default or have two different formulas?

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/homebrew-rdkit#58]
As we seen in `numpy` and `boost-python`, there are two different way to handle the installation.

In `boost-python`, there are two different version of formulas.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python.rb
https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python3.rb

In `numpy`, there are only one formula and install on python and python3 at the same time.
It also has a option to install on python3 only.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/numpy.rb

**Comment by UnixJunkie** [comment]
We only support python3 nowadays, so I think this can be closed.
