### ISSUE TITLE
Add cron job for Travis

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/homebrew-rdkit#63]
As title, I think that will make us find the problem faster.
As I remember, it can be setup like running every day.
@greglandrum Can you setup this for us ?

**Comment by greglandrum** [comment]
Travis runs after ever commit, so there's no need to run it every day.

**Comment by hsiaoyi0504** [comment]
@greglandrum I agree with you that basically, Travis runs after every commit. However, in this repo case, the installation not only depends on the commit of this repo itself, but also depends on upstream **rdkit** repo (HEAD version) and the version of libraries installed installed by **homebrew** (such as **boost-python**). Every commit in **homebrew-core** repo and commit in upstream **rdkit** repo will not start running a Travis travis of this repo. That's the reason why I think it's a need to run it every day.

**Comment by hsiaoyi0504** [comment]
@greglandrum

**Comment by greglandrum** [comment]
ok, I set up the cron job to run daily.
let's see if it helps anything

**Comment by hsiaoyi0504** [comment]
Thanks !
