### ISSUE TITLE
Pin the version of boost, boost-python, boost-python3 in homebrew formula

### ISSUE THREAD

**Issue by hsiaoyi0504** [rdkit/homebrew-rdkit#65]
I think this can avoid several issues we met before in the future like #62. By default, homebrew formula will install latest boost. By pinning the version, we can make sure **rdkit** will be installed by specific boost/boost-python/boost-python3 version. I am currently working on submitting the patches that provide formulas like boost@1.66.

**Comment by hsiaoyi0504** [comment]
As far as I know, 2017_09 and 2018_03 releases are not compatible to boost 1.67 (which is the boost version will be installed by homebrew).

**Comment by mcs07** [comment]
Alternatively, it should be possible to temporarily apply this patch to RDKit for Boost 1.67 compatibility:
https://github.com/rdkit/rdkit/pull/1864

Homebrew patch docs: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#patches

It looks like that PR is scheduled for inclusion in the 2018.09.1 release.

**Comment by hsiaoyi0504** [comment]
You are right, but it seems to me that pinning the version will be more stable compared to fix the dependencies frequently.

**Comment by hsiaoyi0504** [comment]
Just a short update.
It seems that the suggested solution is to maintain our own tap.

https://github.com/Homebrew/homebrew-core/pull/28677#issuecomment-394954498

**Comment by mcs07** [comment]
This repository is the rdkit tap, so you could in theory just put the boost@1.66 formula in the `Formula` directory alongside `rdkit.rb`.

**Comment by hsiaoyi0504** [comment]
Finally got my mac laptop back. I put my current effort here: https://github.com/hsiaoyi0504/homebrew-rdkit/tree/pin_boost_version_2.

However, I meet several problems:
- It seems to me that **DBoost_NO_SYSTEM_PATHS** is not respected, cmake's **find_boost** keep finding the system boost. 
- Not sure how to set the boost python paths
- The building time is too long on Travis.

**Comment by hsiaoyi0504** [comment]
Proposed procedures to be run on local (python3 and using pip install numpy):
``` shell
brew install ./Formula/boost@1.66.rb --build-from-source
brew install ./Formula/boost-python3@1.66.rb --build-from-source
brew install ./Formula/rdkit.rb --build-from-source --with-python3 --without-numpy
```

**Comment by UnixJunkie** [comment]
This is a very good idea in order to make the brew formula for rdkit much more reproducible.

**Comment by UnixJunkie** [comment]
done
