### ISSUE TITLE
Is it normal that gcc is being installed upon install of rdkit on a Mac?

### ISSUE THREAD

**Issue by UnixJunkie** [rdkit/homebrew-rdkit#68]
I thought rdkit is compiled with clang.

I installed this way:
```
brew tap rdkit/rdkit
pip3 install numpy
brew install --HEAD rdkit --with-python3 --with-inchi'
```

**Comment by greglandrum** [comment]
I'm not sure. It doesn't look like we specify that it should use gcc, so maybe it's a homebrew thing.

**Comment by greglandrum** [comment]
Note that I no longer use homebrew and so can't do any maintenance of this package.
I really suggest that you use anaconda (or miniconda) to do RDKit installs if that all possible.

**Comment by UnixJunkie** [comment]
Ok, don't bother too much, I was just curious.

Note that the commands I sent really install rdkit via homebrew (and repeatdly) on the mac I have access to. So, I don't want to give it up.
The only problem I see is that we use --HEAD instead of installing a tagged and released version of rdkit,
which is bad for reproducibility only.

PS: I gave a try at conda, and this is clearly not a tool for me. It gets way too much into my way and doesn't do a system-wide install of rdkit, which is I typically what I want, both on Linux and OS X.

**Comment by UnixJunkie** [comment]
Probably, I am not the only one not having switched to anaconda (@thegodone too?).
