### ISSUE TITLE
Installing on MacBook Air running Mojave failed

### ISSUE THREAD

**Issue by pducrot** [rdkit/homebrew-rdkit#83]
Hi,
Installing on MacBook Air running Mojave 10.14.6 failed with both commands, see error message below. 
Cheers

brew install --HEAD --with-inchi --with-postgresql --with-avalon rdkit
and 
brew install rdkit

CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR python) (Required is at
  least version "1.56.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindBoost.cmake:2161 (find_package_handle_standard_args)
  CMakeLists.txt:262 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/rdkit-20191123-477-1laiqx0/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/rdkit/homebrew-rdkit/issues

**Comment by UnixJunkie** [comment]
You should try adding '--with-python3' to your options.
I guess it will force installing the missing dependency.

**Comment by pducrot** [comment]
brew install --HEAD --with-inchi --with-postgresql --with-avalon --with-python3 rdkit

still failing:
CMake Error at /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR python) (Required is at
  least version "1.56.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/FindBoost.cmake:2161 (find_package_handle_standard_args)
  CMakeLists.txt:262 (find_package)

**Comment by UnixJunkie** [comment]
Maybe you do have boost, but it is too old.
Try this:
```
brew reinstall boost boost-python3
```
If this work, check the version that was installed, then retry to install rdkit.

**Comment by pducrot** [comment]
For those who might have similar issues: 
- /usr/local/lib/cmake folder had wrong access rights due to former installations (2014!)
- boost didn't link properly and was probably absent of rdkit 2018 install
    Error: Could not symlink lib/cmake/boost_numpy-1.71.0
- some dependencies were built with different standard
    Warning boost-python3 dependency gcc was built with a different C++ standard

Solution
- updated cmake access rights
- reinstalled rdkit from scratch, with neither the --HEAD nor the --with-postgresql options

**Comment by UnixJunkie** [comment]
Thanks for documenting your solution.
Brew builds are not super reproducible...
