### ISSUE TITLE
Could NOT find Boost (missing: python) (found suitable version "1.72.0",   minimum required is "1.56.0")

### ISSUE THREAD

**Issue by aravind1338** [rdkit/homebrew-rdkit#89]
**Configuration:**

RDKit Version: with Python3
Operating system: macOS 10.15.5
Python version (if relevant):
how did you install the RDKit? Using the command

```
brew install --with-python3 rdkit
```

**Description:**

The installation downloads all the dependencies, but it throws an error "Could NOT find Boost (missing: python) (found suitable version "1.72.0",   minimum required is "1.56.0")". 

I'm new to downloading stuff with brew, so I'm not quite sure what to do.

**Comment by UnixJunkie** [comment]
probably related to https://github.com/rdkit/homebrew-rdkit/issues/87

**Comment by UnixJunkie** [comment]
probably also related to https://github.com/rdkit/rdkit/issues/3030

**Comment by whymauri** [comment]
Try this:

```
cd /usr/local/lib
 sudo ln -s $(ls | grep -Eo libboost_python3[0-9].dylib) libboost_python3.dylib
```
Based on: https://github.com/rdkit/rdkit/issues/1995#issuecomment-411263663
Cheers.

**Comment by UnixJunkie** [comment]
@whymauri this fixes the compilation, however, you cannot import rdkit from python after that.

**Comment by UnixJunkie** [comment]
You might try this:
```bash
# backup your brew installed packages list
brew list --formula > my_brew_packages.txt
# uninstall all of them
brew uninstall --force $(cat my_brew_packages.txt)
# install rdkit from scratch
brew install rdkit --with-python3
```
