### ISSUE TITLE
Add rdkit.egg-info directory

### ISSUE THREAD

**Issue by flying-sheep** [rdkit/homebrew-rdkit#97]
That metadata allows tools like pip and IDEs to detect that the package is installed.

**Comment by UnixJunkie** [comment]
A pull request to support this would be welcome.

**Comment by zymergen-luke** [comment]
egg-info files are usually generated automatically when the package is
installed. The typical use-case would be if you are performing a
development install of a package. e.g. `pip install -e path/to/rdkit`. That
will generate an installed link pointing to your rdkit directory and
generate the .egg-info directory automatically. (Note: this is based on my
previous experience, I haven't tested this specifically with rdkit).

Would you mind double checking that you can't pip install rdkit with the
`-e` option to get what you want? Is there some other workflow you are
trying to achieve?

-Luke

**Comment by UnixJunkie** [comment]
@zymergen-luke to the best of my knowledge, rdkit cannot be installed with pip.
https://github.com/rdkit/rdkit/issues/1812
Several people are interested into having it work, they might even accept some help.

**Comment by flying-sheep** [comment]
Yes, this issue is about adding correct metadata no matter how it can be installed.

That would make tools see that RDkit is installed, and allow people to add it to their dependencies.

The way things are now, trying to install a package depending on RDkit results in your package manager (likely pip) to complain that it can’t find a way to install RDkit, despite RDkit being already installed.

**Comment by zymergen-luke** [comment]
Thanks for the clarification!

-Luke

**Comment by UnixJunkie** [comment]
Well, someone has to contribute this.
And I even wonder if this is not an rdkit issue (this repository is just one brew install recipe for rdkit).

**Comment by UnixJunkie** [comment]
This is an rdkit issue, so closing:
Cf. https://github.com/rdkit/rdkit/pull/2690
Comment in there if you want things to progress.
