### ISSUE TITLE
rdkit installation problem in mac os catelina

### ISSUE THREAD

**Issue by yellaboina** [rdkit/homebrew-rdkit#98]
==> Installing rdkit from rdkit/rdkit
==> Downloading https://github.com/rdkit/rdkit/archive/Release_2020_03_4.tar.gz
Already downloaded: /Users/sailu/Library/Caches/Homebrew/downloads/4839f1a506ffb63c0c0ad7e6fac8fb3037e44075a4d0fde085d1eb71ed06b19a--rdkit-Release_2020_03_4.tar.gz
detected clang C++ compiler
==> cmake -DRDK_INSTALL_INTREE=OFF -DRDK_BUILD_CPP_TESTS=OFF -DRDK_INSTALL_STATIC_LIBS=OFF -DBoost_NO_BOOST_CMAKE=ON -DPYTHON_EXECUTABLE='/usr/local/opt/python@3.8/bin/python3' -DPY
Last 15 lines from /Users/sailu/Library/Logs/Homebrew/rdkit/01.cmake:
Call Stack (most recent call first):
  CMakeLists.txt:255 (find_package)

CMake Error at /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Boost (missing: python) (found suitable version "1.73.0",
  minimum required is "1.56.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindBoost.cmake:2177 (find_package_handle_standard_args)
  CMakeLists.txt:263 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/rdkit-20200828-14861-r5jjpk/rdkit-Release_2020_03_4/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/rdkit/homebrew-rdkit/issues

These open issues may also help:
Add rdkit.egg-info directory https://github.com/rdkit/homebrew-rdkit/issues/97

**Comment by UnixJunkie** [comment]
Try to reinstall everything. E.g.
```
brew update
brew remove boost boost-python3 rdkit
brew install rdkit --with-python3
```

**Comment by UnixJunkie** [comment]
You could try this also:
```bash
# backup your brew installed packages list
brew list --formula > my_brew_packages.txt
# uninstall all of them
brew uninstall --force $(cat my_brew_packages.txt)
# install rdkit from scratch
brew install rdkit --with-python3
```
