### ISSUE TITLE
RDKIt PostgreSQL cartrdige via brew

### ISSUE THREAD

**Issue by MQSchleich** [rdkit/homebrew-rdkit#99]
Hey, 

I encountered an error during the installation on Catalina 10.15.7.

>Error: An exception occurred within a child process:
 >Errno::ENOENT: No such file or directory @ rb_file_s_rename - (Code/PgSQL/rdkit/rdkit.sql91.in, Code/PgSQL/rdkit/rdkit--3.4.sql)

Do you know how to fix it? 

Thanks :)

**Comment by UnixJunkie** [comment]
How did you install (which commands exactly)?

**Comment by MQSchleich** [comment]
Thank you for your answer. I installed RDKit with tho following commands: 

`brew install rdkit --with-inchi --with-avalon --with-postgresql`

**Comment by UnixJunkie** [comment]
I really have no idea.
You should ask on the rdkit users mailing-list.
You can try this but there is not any guarantee that it will work:
```
brew install --HEAD rdkit --with-inchi --with-avalon --with-postgresql
```

**Comment by MQSchleich** [comment]
> brew install --HEAD rdkit --with-inchi --with-avalon --with-postgresql

Thank you for your reply. The  --HEAD option did not produce any different result.

**Comment by UnixJunkie** [comment]
You can try the conda install recipe from rdkit.
This is the official default install method.
Or, as on the mailing list.

**Comment by MQSchleich** [comment]
Thanks, I will try. However, I hoped to integrate it into my existing environment. Is there any possibility of just releasing the pg-extension? It would make life easier.

**Comment by UnixJunkie** [comment]
I don't use PGSQL, ask what you need on the rdkit mailing list.
I don't want to deal with things that I don't use personally and have no way to test.

**Comment by UnixJunkie** [comment]
Maybe you can give a try at the new rdkit formula in brew master repository.
They turn on PGSQL by default.
